version: '3.9'
services:
  db:
    image: mysql:5.7.38-debian
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password1
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./cloudsql:/cloudsql
  web:
    build:
      context: .
      args:
        DEPLOY_ENV: development
    # command: sh -c "rm -f tmp/pid/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    command: /bin/sh
    volumes:
      - .:/app
      - ./cloudsql:/cloudsql
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    # user: 1000:1000
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=Password1
    ports:
      - "81:80"
  solargraph:
    build: .
    command: bundle exec solargraph socket --host=0.0.0.0 --port=7658
    volumes:
      - .:/app
      # - bundle:/usr/local/bundle
    ports:
      - "7658:7658"
volumes:
  db_data: